language: cpp
install: make get-deps

script:
  - CONTROL=SINE make
  - make clean
  - CONTROL=FOC make

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded

